### ISSUE TITLE
grunt serve failing

### ISSUE THREAD

**Issue by CombatCode** [jprystowsky/generator-hyper-angular#5]
after i type grunt serve command:

```
Running "express:development" (express) task
Starting background Express server

Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/home/combat/.dev/us/us-core-hyper/node_modules/express/lib/express.js:89:13)
    at module.exports (/home/combat/.dev/us/us-core-hyper/express/config/express.js:11:19)
    at /home/combat/.dev/us/us-core-hyper/app.js:10:37
    at Object.<anonymous> (/home/combat/.dev/us/us-core-hyper/app.js:16:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by jprystowsky** [comment]
@CombatCode Thanks. It looks like Express updated their API. I've pushed up a new version to npm that should address this. If you haven't done anything since you generated the project, just update generator-hyper-angular and rerun yo hyper-angular and let it overwrite. Otherwise, see https://github.com/jprystowsky/generator-hyper-angular/commit/6820d91bdda38ee1923bc72fe83232b875fe722c and adjust your code similarly.
